apiVersion: backstage.io/v1beta2
kind: Component
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta2 template demo
spec:
  owner: backstage/techdocs-core
  type: service
  lifecycle: experimental
